var Product = require('../models/product');
var mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/boticstechnologiesdb', { useNewUrlParser: true }, (err, res) => {
if (err) throw err;
console.log('Database online');
});
var carts = [
  new Product({
    item_category:'Arduino',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    detailed_description:'this is a detailed description',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    detailed_description:'this is a detailed description',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    detailed_description:'this is a detailed description',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Kits',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Analog Sensors',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Digital Sensors',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Cellulars',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'Integrated circuits',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Batteries',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Cables',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Displays',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
  new Product({
    item_category:'Wireless modules',
    imagePath_one:'1.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image one',
    description:'Image one  description',
    detailed_description:'this is a detailed description',
    price:60,
    quantities:2,
    orders:1245,
    feedback:''
  }),
  new Product({
    item_category:'Breakout boards',
    imagePath_one:'2.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image two',
    description:'Image two  description',
    detailed_description:'this is a detailed description',
    price:120,
    quantities:4,
    orders:87532,
    feedback:''
  }),
  new Product({
    item_category:'PCB enclosures and Cases',
    imagePath_one:'3.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image three',
    description:'Image three  description',
    detailed_description:'this is a detailed description',
    price:240,
    quantities:7,
    orders:694,
    feedback:''
  }),
  new Product({
    item_category:'Power Supply',
    imagePath_one:'4.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image four',
    description:'Image four  description',
    detailed_description:'this is a detailed description',
    price:480,
    quantities:9,
    orders:43,
    feedback:''
  }),
  new Product({
    item_category:'Arduino',
    imagePath_one:'5.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image five',
    description:'Image five  description',
    detailed_description:'this is a detailed description',
    price:960,
    quantities:33,
    orders:341,
    feedback:''
  }),
  new Product({
    item_category:'Raspberry pi',
    imagePath_one:'6.jpg',
    imagePath_two:'',
    imagePath_three:'',
    imagePath_four:'',
    title:'Image six',
    description:'Image six  description',
    detailed_description:'this is a detailed description',
    price:1920,
    quantities:6,
    orders:5,
    feedback:''
  }),
];

var done=0;

for(var i=0;i<carts.length;i++){
   carts[i].save(function (err,result) {
     if (err) {
       console.log(err);
     }
     done++;
     if(done===Product.lenth){
       exit();
     }
   });
}

function exit() {
  console.log('data saved successfully!');
mongoose.disconnect();
}
